name: Crawling

on:
  schedule:
    - cron: "0 0 * * *" # At 00:00
  workflow_dispatch:

jobs:
  build:
    name: Trigger crawler
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"secret":"${{ secrets.CRAWL_SECRET }}"}' ${{ secrets.CRAWL_URL }}
