# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: |
          cd src/backend
          go get -v -t -d ./...

      - name: Build
        run: |
          cd src/backend
          go build -v ./...

      - name: Test
        run: |
          cd src/backend
          go test -v ./...
