# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: |
          cd src/backend
          go get -v ./...

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report@latest
        # Ensure that the GOPATH/bin is in the PATH
        env:
          GOPATH: ${{ env.GOPATH }}

      - name: Build
        run: |
          cd src/backend
          go build -v ./...

      - name: Test
        run: |
          cd src/backend
          go test ./... -json | $(go env GOPATH)/bin/go-junit-report > TestResults.xml

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: src/backend/TestResults.xml

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Go Tests
          path: src/backend/TestResults.xml
          reporter: junit
